---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: user-service
  labels:
    app: user-service
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pttgc01acr.azurecr.io/user-service:unstable
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

